### ISSUE TITLE
### Summary

### ISSUE THREAD

**Issue by Catclaws12** [mdn/browser-compat-data#13679]
### Summary

I was [Configuring a Federated SSSD Store](https://www.keycloak.org/docs/latest/server_admin/#configuring-a-federated-sssd-store) per Keycloak's documentation [SSSD and FreeIPA Identity Management Integration](https://www.keycloak.org/docs/latest/server_admin/#sssd-and-freeipa-identity-management-integration) using ansible collection [community.general](https://github.com/ansible-collections/community.general) from the main branch on Github. Currently I am able to implement this by editing [keycloak_user_federation.py](https://github.com/ansible-collections/community.general/blob/main/plugins/modules/identity/keycloak/keycloak_user_federation.py#L768) Line 768 and adding 'sssd' to the array. However, I would not be able to use ansible's requirements.yml file for continuous deployment(s). Alot of our Red Hat customers that leverage RHSSO/Keycloak often have Red Hat IDM/IPA in their environment. It would be nice to automate this process via this collection.

### Issue Type

Feature Idea

### Component Name

[keycloak_user_federation.py](https://github.com/ansible-collections/community.general/blob/main/plugins/modules/identity/keycloak/keycloak_user_federation.py)

### Additional Information

```yaml (paste below)
---
- hosts: localhost  ## assuming localhost == keycloak.example.com
  connection: local
  tasks:

  - name: Enable SSSD user storage federation
    community.general.keycloak_user_federation:
      auth_keycloak_url: http://localhost:8080/auth
      auth_realm: master
      auth_username: admin
      auth_password: password
      realm: master
      name: sssd
      state: present
      provider_id: sssd
      provider_type: org.keycloak.storage.UserStorageProvider
      #config:
      #  cachePolicy: NO_CACHE
    register: sssd_user_storage_provider
    failed_when:
      - "'No changes required to user federation' not in sssd_user_storage_provider.msg"
      #- "'has been updated' not in sssd_user_storage_provider.msg"   ## ONLY add this line when updating config.cachePolicy var
      - ('Could not create component in realm' not in sssd_user_storage_provider.msg) or
        ('HTTP Error 400{{":"}} Bad Request' in sssd_user_storage_provider.msg)
```

Current output on first run, NO CACHE POLICY
```
ok: [rhsso.jlabs.com] => {
    "ansible_facts": {
        "discovered_interpreter_python": "/usr/bin/python"
    }, 
    "changed": false, 
    "diff": {}, 
    "end_state": {
        "config": {
            "cachePolicy": "DEFAULT", 
            "enabled": "true", 
            "priority": "0"
        }, 
        "id": "2a56db18-30f5-4662-967e-405c2895b06f", 
        "mappers": [], 
        "name": "sssd", 
        "parentId": "master", 
        "providerId": "sssd", 
        "providerType": "org.keycloak.storage.UserStorageProvider"
    }, 
    "existing": {
        "config": {
            "cachePolicy": "DEFAULT", 
            "enabled": "true", 
            "priority": "0"
        }, 
        "id": "2a56db18-30f5-4662-967e-405c2895b06f", 
        "mappers": [], 
        "name": "sssd", 
        "parentId": "master", 
        "providerId": "sssd", 
        "providerType": "org.keycloak.storage.UserStorageProvider"
    }, 
    "failed_when_result": false, 
    "invocation": {
        "module_args": {
            "auth_client_id": "admin-cli", 
            "auth_client_secret": null, 
            "auth_keycloak_url": "http://localhost:8080/auth", 
            "auth_password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER", 
            "auth_realm": "master", 
            "auth_username": "admin", 
            "config": null, 
            "id": null, 
            "mappers": null, 
            "name": "sssd", 
            "parent_id": null, 
            "provider_id": "sssd", 
            "provider_type": "org.keycloak.storage.UserStorageProvider", 
            "realm": "master", 
            "state": "present", 
            "token": null, 
            "validate_certs": true
        }
    }, 
    "msg": "No changes required to user federation 2a56db18-30f5-4662-967e-405c2895b06f.", 
    "proposed": {}
}
Read vars_file 'vault.yml'
META: ending play

PLAY RECAP ************************************************************************************
rhsso.jlabs.com            : ok=1    changed=0    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0
```

In fact this actually do enable SSSD User Store Federation dispite the output message of "No changes required"

Second run, with changing cachePolicy to NO_CACHE

```
changed: [rhsso.jlabs.com] => {
    "ansible_facts": {
        "discovered_interpreter_python": "/usr/bin/python"
    }, 
    "changed": true, 
    "diff": {}, 
    "end_state": {
        "config": {
            "cachePolicy": "DEFAULT", 
            "enabled": "true", 
            "priority": "0"
        }, 
        "id": "2a56db18-30f5-4662-967e-405c2895b06f", 
        "mappers": [], 
        "name": "sssd", 
        "parentId": "master", 
        "providerId": "sssd", 
        "providerType": "org.keycloak.storage.UserStorageProvider"
    }, 
    "existing": {
        "config": {
            "cachePolicy": "DEFAULT", 
            "enabled": "true", 
            "priority": "0"
        }, 
        "id": "2a56db18-30f5-4662-967e-405c2895b06f", 
        "mappers": [], 
        "name": "sssd", 
        "parentId": "master", 
        "providerId": "sssd", 
        "providerType": "org.keycloak.storage.UserStorageProvider"
    }, 
    "failed_when_result": false, 
    "invocation": {
        "module_args": {
            "auth_client_id": "admin-cli", 
            "auth_client_secret": null, 
            "auth_keycloak_url": "http://localhost:8080/auth", 
            "auth_password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER", 
            "auth_realm": "master", 
            "auth_username": "admin", 
            "config": {
                "allowKerberosAuthentication": [
                    "false"
                ], 
                "authType": [
                    "none"
                ], 
                "batchSizeForSync": [
                    "1000"
                ], 
                "cachePolicy": [
                    "NO_CACHE"
                ], 
                "changedSyncPeriod": [
                    "-1"
                ], 
                "connectionPooling": [
                    "true"
                ], 
                "enabled": [
                    "true"
                ], 
                "fullSyncPeriod": [
                    "-1"
                ], 
                "importEnabled": [
                    "true"
                ], 
                "pagination": [
                    "true"
                ], 
                "priority": [
                    "0"
                ], 
                "searchScope": [
                    "1"
                ], 
                "startTls": [
                    "false"
                ], 
                "syncRegistrations": [
                    "false"
                ], 
                "trustEmail": [
                    "false"
                ], 
                "useKerberosForPasswordAuthentication": [
                    "false"
                ], 
                "usePasswordModifyExtendedOp": [
                    "false"
                ], 
                "useTruststoreSpi": [
                    "ldapsOnly"
                ], 
                "validatePasswordPolicy": [
                    "false"
                ]
            }, 
            "id": null, 
            "mappers": null, 
            "name": "sssd", 
            "parent_id": null, 
            "provider_id": "sssd", 
            "provider_type": "org.keycloak.storage.UserStorageProvider", 
            "realm": "master", 
            "state": "present", 
            "token": null, 
            "validate_certs": true
        }
    }, 
    "msg": "User federation 2a56db18-30f5-4662-967e-405c2895b06f has been updated", 
    "proposed": {
        "config": {
            "allowKerberosAuthentication": "false", 
            "authType": "none", 
            "batchSizeForSync": "1000", 
            "cachePolicy": "NO_CACHE", 
            "changedSyncPeriod": "-1", 
            "connectionPooling": "true", 
            "enabled": "true", 
            "fullSyncPeriod": "-1", 
            "importEnabled": "true", 
            "pagination": "true", 
            "priority": "0", 
            "searchScope": "1", 
            "startTls": "false", 
            "syncRegistrations": "false", 
            "trustEmail": "false", 
            "useKerberosForPasswordAuthentication": "false", 
            "usePasswordModifyExtendedOp": "false", 
            "useTruststoreSpi": "ldapsOnly", 
            "validatePasswordPolicy": "false"
        }
    }
}
Read vars_file 'vault.yml'
META: ending play

PLAY RECAP ************************************************************************************
rhsso.jlabs.com            : ok=1    changed=1    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0  
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct

__Originally posted by @jayissi in https://github.com/ansible-collections/community.general/issues/3767__
