### ISSUE TITLE
`<ratio>` with `<number> / <number>` or `<number>` seems to be support since Firefox 78

### ISSUE THREAD

**Issue by romainmenke** [mdn/browser-compat-data#18198]
https://github.com/mdn/browser-compat-data/blob/2e205a9b65d23a216ca246e9d619974098465910/css/types/ratio.json#L53-L62

see : https://mrhenry.github.io/web-tests/#de023e11-f61a-4635-a74c-e4a152251bdf

From Firefox 78 all these variants of `<ratio>` seem to pass :

```css
@media screen and (min-aspect-ratio: 1/100) {
	#a {
		color: #0f0;
	}
}

@media screen and (min-aspect-ratio: 0.01/1) {
	#b {
		color: #0f0;
	}
}

@media screen and (min-aspect-ratio: 0.01) {
	#c {
		color: #0f0;
	}
}

#d {
	color: #0f0;
}

@media screen and (min-aspect-ratio: 0/0) {
	#d {
		color: red;
	}
}

@media screen and (max-aspect-ratio: 0/0) {
	#e {
		color: #0f0;
	}
}

@media screen and (min-aspect-ratio: calc(1)/calc(10*10)) {
	#f {
		color: #0f0;
	}
}

@media screen and (min-aspect-ratio: calc(1/100)) {
	#g {
		color: #0f0;
	}
}
```

**Comment by romainmenke** [comment]
_This is more complicated than I had hoped._

Browsers do not consistently support the `<ratio>` value type. There are difference between `aspect-ratio` property and `aspect-ratio` media feature.

Full support for `<ratio>` means :
- allow single value
- allow non-integer values in either component (static values or results from `calc()`)

--------

For documentation purposes it might be best to split these up or to otherwise make it clear to users what does and does not work today.

Currently there are these three pages :
- https://developer.mozilla.org/en-US/docs/Web/CSS/ratio
- https://developer.mozilla.org/en-US/docs/Web/CSS/@media/aspect-ratio
- https://developer.mozilla.org/en-US/docs/Web/CSS/aspect-ratio

The `<ratio>` type also links to the media queries specification but it should link to : https://www.w3.org/TR/css-values-4/#ratios

Both the media feature and the property do not show any warning or detailed info about `<ratio>` type support. They both depend on the `<ratio>` specific page for that information. But this support is specific to where the type is used.

Firefox has full support for `<ratio>` in the `aspect-ratio` media feature since Firefox 78 but this is shows as "behind a flag".

All other browsers only have support for two integer values in the `aspect-ratio` media feature.

All browsers have full support for `<ratio>` in the `aspect-ratio` property since it was added.

----------

Some spot tests for the `aspect-ratio` property :

```css
.box-with-aspect-ratio-a {
	aspect-ratio: calc(16/9);
	background-color: pink;
	width: 100px;
}

.box-with-aspect-ratio-b {
	aspect-ratio: 1.77;
	background-color: purple;
	width: 100px;
}

.box-with-aspect-ratio-c {
	aspect-ratio: calc(1.77);
	background-color: hotpink;
	width: 100px;
}
```

<img width="963" alt="Screenshot 2022-11-13 at 09 59 34" src="https://user-images.githubusercontent.com/11521496/201514630-c60614b7-9727-48b9-842a-8c4c2fd10906.png">

<img width="932" alt="Screenshot 2022-11-13 at 10 01 06" src="https://user-images.githubusercontent.com/11521496/201514632-2695e9a8-4de9-4f83-86fd-60bebcba0b49.png">

<img width="943" alt="Screenshot 2022-11-13 at 09 59 01" src="https://user-images.githubusercontent.com/11521496/201514627-f09ccbf9-915f-49c6-bb2a-afca79fafe55.png">
