### ISSUE TITLE
hsl() - IE11 does not support `<angle>` values as the first argument of `hsl()`

### ISSUE THREAD

**Issue by Goodwine** [mdn/browser-compat-data#18906]
### What type of issue is this?

Missing compatibility data

### What information was incorrect, unhelpful, or incomplete?

IE11 doesn't support `<angle>` units in `hsl()`. 

### What did you expect to see?

I expect to see:

```json
"partial_implementation": true,
"notes": "Internet Explorer doesn't support any units such as `deg` or `rad` for hsl angles."
```

### Did you test this? If so, how?

```css
.box {
  height: 50px;
  background: hsl(200deg, 100%, 50%); /* fails because of "deg" units */
}
```

However, it does work when removing the units:
```css
.box {
  height: 50px;
  background: hsl(200, 100%, 50%); /* works */
}
```

### Do you have anything more you want to share?

FWIW - `<angle>` does work in IE11, for example `transform: rotate(45deg);` works fine.
The problem is only in `hsl(<angle>, ...)`
