### ISSUE TITLE
css.types.basic-shape.path - <SUMMARIZE THE PROBLEM>

### ISSUE THREAD

**Issue by nassosyian** [mdn/browser-compat-data#20004]
### What type of issue is this?

Incorrect support data (example: Chrome says "86" but support was added in "40")

### What information was incorrect, unhelpful, or incomplete?

path() is now supported by the latest version of Safari

### What did you expect to see?

Safari supports it

### Did you test this? If so, how?

tested it on Safari v16.4

### MDN URL

https://developer.mozilla.org/en-US/docs/Web/CSS/path

### MDN metadata

<details>
<summary>MDN page report details</summary>

* Query: `css.types.basic-shape.path`
* Report started: 2023-06-01T14:25:11.906Z

</details>

**Comment by iFreilicht** [comment]
I can confirm this. Even MDN itself has the correct information on [the page for the clip-path property](https://developer.mozilla.org/en-US/docs/Web/CSS/clip-path#browser_compatibility).

This was also reported already in #15961.

I tested in Firefox, Safari and Chrome. Specifically, [this codepen](https://codepen.io/iFreilicht/pen/XWyWdbz):

```css
#trapezoid {
  position: relative;
  width: 200px;
  height: 50px;
  bottom: 100px;
  background-color: orange;
  clip-path: path('M 0 50 L 40 0 L 160 0 L 200 50 Z');
}

#trapezoid:hover {
  background-color: white;
}
```

This correctly clips the corners of the rectangle to form a trapezoid, and the hover will only trigger when hovering the clipped shape, not when hovering the original shape/bounding box.

Even the examples on MDN all work in all three browsers.
