### ISSUE TITLE
`background-blend-mode` - iOS Safari: Ignored when repeating background

### ISSUE THREAD

**Issue by strarsis** [mdn/browser-compat-data#20308]
### What type of issue is this?

Incorrect support data (example: Chrome says "86" but support was added in "40")

### What information was incorrect, unhelpful, or incomplete?

`background-blend-mode` is not applied by iOS/iPad OS Safari when the background also repeats (additionally depending on `background-size` values).

When `background-blend-mode` is used together with a `background-color`, iOS/iPad OS Safari will not blend the background image when the background is also repeated. This bug does not solely depend on just the background repeat, as it may or may not work sometimes depending on what is used as `background-size`: When `background-size` is smaller than 79% of its size, `background-blend-mode` is also applied in a repeating background.

CodePen: https://codepen.io/strarsis/pen/poQWPOX

### What browsers does this problem apply to, if applicable?

Safari

### What did you expect to see?

`background-blend-mode` correctly applied iOS/iPad OS Safari, as in the other browsers.

### Did you test this? If so, how?

I encountered the issue while testing on an iPad device. Then I created a test case to isolate the cause of the problem in iOS/iPad OS Safari.

CodePen: https://codepen.io/strarsis/pen/poQWPOX

### Can you link to any release notes, bugs, pull requests, or MDN pages related to this?

https://stackoverflow.com/questions/35452263/css-a-background-blend-mode-fallback-for-iphone-safari

**Comment by strarsis** [comment]
So new findings: It has something to do with the element width or height being larger than `256px` and the `background-size` `width` and `height` being smaller than `256px` (even by just one pixel). `256` is a typical size used for allocating things, so this hints towards some memory issue in iOS/iPad OS Safari browser.

**Comment by strarsis** [comment]
Feature test: https://codepen.io/strarsis/pen/YzRrbaZ

**Comment by strarsis** [comment]
Webkit bug report: https://bugs.webkit.org/show_bug.cgi?id=259081

**Comment by queengooborg** [comment]
Hey @strarsis, thanks for tracking this down and doing all of this research!  Would you be down to open a pull request to update the data accordingly?

**Comment by strarsis** [comment]
@queengooborg: Where can I find the configuration/code for adding notes?
https://github.com/mdn/browser-compat-data/blob/main/css/properties/background-blend-mode.json

On the [`background-blend-mode` Can I use page](https://caniuse.com/css-backgroundblendmode) are already notes as `1Partial in Safari refers to not supporting the hue, saturation, color, and luminosity blend modes.`. I want to add an additional note like this.

**Comment by queengooborg** [comment]
> Edit: I found the right file for this: https://github.com/Fyrd/caniuse/blob/main/features-json/css-backgroundblendmode.json

Oh that file is for CanIUse, not for BCD!  The BCD file is here: https://github.com/mdn/browser-compat-data/blob/main/css/properties/background-blend-mode.json

**Comment by FaisalHet** [comment]
https://app.intercom.com/a/inbox/hrpt54hy/inbox/admin/2048371/conversation/215470456788004

**Comment by Sparronator9999** [comment]
I have also run into this issue while developing my website. The solution for me was to use a nested element to do the background image filtering (here implemented with the `::before` pseudo-element).

So instead of the following example CSS (which would trigger the bug):

```css
.filtered-bg
{
    /* image must have a length or width of 256px or higher to trigger the bug!
     * magenta is used for the background colour to make the bug more obvious
     * (assuming your background isn't already magenta...) */
    background: #ff00ff url("bg.png");
    background-blend-mode: multiply;
    width: 640px;
    height: 480px;
}
```

You could instead write:

```css
.filtered-bg-fixed
{
    background: url("bg.png");
    width: 640px;
    height: 480px;
    position: relative;
}
.filtered-bg-fixed::before
{
    background: #ff00ff;
    content: "";
    mix-blend-mode: multiply;
    position: absolute;
    left: 0;
    top: 0;
    right: 0;
    bottom: 0;
}
```

If the `div` you're applying the fix to has any content, you'll want to place it in a nested container `div` (if you haven't already) with the following code, otherwise it will also be filtered with the "fixed" code:

```css
.filtered-bg-content
{
    position: absolute;
    left: 0;
    top: 0;
    right: 0;
    bottom: 0;
    /* z-index wasn't needed for me here, but may be depending on how you use this CSS */
}
```

I don't have CodePen to write a demonstration, but I might make a page on my website showing off the bug.
