### ISSUE TITLE
css.at-rules.page - margin at-rules and margin at-rule styles compatibility is missing

### ISSUE THREAD

**Issue by ArianeBouchardConformit** [mdn/browser-compat-data#21403]
### What type of issue is this?

Missing compatibility data

### What information was incorrect, unhelpful, or incomplete?

Most of the possibilities offered by `@page` and its sub-at-rules are not supported by any browser yet. A warning box says this in the content, but a quick look at the compatibility table seems to say everything is supported.

### What browsers does this problem apply to, if applicable?

Chromium (Chrome, Edge 79+, Opera, Samsung Internet), Firefox, Legacy Edge (12-18), Safari

### What did you expect to see?

Considering you can't do much with `@page` right now, I think it'd be important to add rows to the table that show that at-rules such as `@bottom-left` are not supported anywhere yet.

OR there could be a separate page for each at-rule that lists every possible CSS rule for the at-rule and what supports it. It'd be all "No" for now, though, of course.

### Did you test this? If so, how?

Tried to do something like this

```css

@page {
   @bottom-right {
      content: "!!Page " counter(page) " of " counter(pages);
   }
   @bottom-left-corner {
      content: "!!Page " counter(page) " of " counter(pages);
   }

   @bottom-left {
      content: "!!Page " counter(page) " of " counter(pages);
   }

   @left-bottom {
      content: "!!Page " counter(page) " of " counter(pages);
   }

   @bottom-center {
      content: "!!Page " counter(page) " of " counter(pages);
   }
}
```

### MDN URL

https://developer.mozilla.org/en-US/docs/Web/CSS/@page

### MDN metadata

<details>
<summary>MDN page report details</summary>

* Query: `css.at-rules.page`
* Report started: 2023-11-30T16:55:17.810Z

</details>
