### ISSUE TITLE
css.properties.letter-spacing - <Google chrome handle letter spacing diff>

### ISSUE THREAD

**Issue by PhamManh2911** [mdn/browser-compat-data#21807]
### What type of issue is this?

Other

### What information was incorrect, unhelpful, or incomplete?

Text paragraph display unexpectedly according to changing letter spacing

### What browsers does this problem apply to, if applicable?

Chromium (Chrome, Edge 79+, Opera, Samsung Internet)

### What did you expect to see?

Consistent display between multiple browser, I've tested on chrome, fire fox and safari

### Did you test this? If so, how?

I've tested the same css code in google chrome, fire fox and safari

### Do you have anything more you want to share?

The font family though is not verified by google font. I'm using HLT Bellissima Script Pro.
On firefox and safari, the paragraph display the same style, but on google chrome the style change when letter spacing enable.
Here is how my css code looks like.
```css
p {
    letter-spacing: 0.00938em;
    /* disable letter-spacing to see the difference */
    color: #040f1e;
    font-family: "__bellissima_b3fbf3", "__bellissima_Fallback_b3fbf3";
    font-size: 57px;
    line-height: 64px;
    font-weight: 400;
    text-align: center;
}
```
Font used is HLT Bellissima Script Pro. I'm using nextjs as full-stack framework, so I download the font family to source code and using it through ```localFont```(FYI, I think this is not the problem cause the difference only happens on google chrome when changing letter spacing)

### MDN URL

https://developer.mozilla.org/en-US/docs/Web/CSS/letter-spacing

### MDN metadata

<details>
<summary>MDN page report details</summary>

* Query: `css.properties.letter-spacing`
* Report started: 2024-01-02T04:45:21.712Z

</details>
