### ISSUE TITLE
@media "scan" feature - missing

### ISSUE THREAD

**Issue by estelle** [mdn/browser-compat-data#21990]
### What type of issue is this?

Missing compatibility data

### What information was incorrect, unhelpful, or incomplete?

https://drafts.csswg.org/mediaqueries/#scan is missing from https://github.com/mdn/browser-compat-data/blob/main/css/at-rules/media.json

The media feature is present in mediaqueries levels 3, 4 and 5.

### What did you expect to see?

This feature listed in bcd.

### HTML

```html
<p>This is a test.</p>
```

### CSS

```css
p {
  padding: 10px;
  border: solid;
}

@media (scan: interlace) {
  p {
    background: #f4ae8a;
  }
}
@media (scan: progressive) {
  p {
    text-decoration: underline;
  }
}
@media not (scan: progressive) {
  p {
    border-style: dashed;
  }
}
@media not (scan: interlaced) {
  p {
    color: purple;
  }
}
```

Safari and FF dash the border on a modern laptop (MBP). Chrome and edge do nothing. I would have assumed the text would be underlined and purple, but that was not the case.
