### ISSUE TITLE
Margin at rules - invalid support data css.at-rules.page - current Edge supports Margin at rules.

### ISSUE THREAD

**Issue by MattiJarvinen** [mdn/browser-compat-data#25799]
### What type of issue is this?

Incorrect support data (example: BrowserX says "86" but support was added in "40")

### What information was incorrect, unhelpful, or incomplete?

Edge margin at rule support

Edge 132.0.2957.127 (Official build) (64-bit)  seems to support margin at rules. At least content: '' property.

### What browsers does this problem apply to, if applicable?

Chromium (Chrome, Edge 79+, Opera, Samsung Internet)

### What did you expect to see?

Edge should have supported listed since 131.0.2903.48

### Did you test this? If so, how?

By testing

``` css
@page {
  size: A4 landscape;

  margin: 2.25pt 0;

  @top-left-corner {
    content: "@top-left-corner";
  }
  @top-left {
    content: "@top-left";
  }
  @top-center {
    content: "@top-center";
  }
  @top-right {
    content: "@top-right";
  }
  @top-right-corner {
    content: "@top-right-corner";
  }
  @bottom-left-corner {
    content: "@bottom-left-corner";
  }
  @bottom-left {
    content: "@bottom-left";
  }
  @bottom-center {
    content: "@bottom-center";
  }
  @bottom-right {
    content: "@bottom-right";
  }
  @bottom-right-corner {
    content: "@bottom-right-corner";
  }

  @left-top {
    content: "@left-top";
  }
  @left-middle {
    content: "@left-middle";
  }
  @left-bottom {
    content: "@left-bottom";
  }
  @right-top {
    content: "@right-top";
  }
  @right-middle {
    content: "@right-middle";
  }
  @right-bottom {
    content: "@right-bottom";
  }
}
```

![Image](https://github.com/user-attachments/assets/5f48feb5-45ab-441f-b9df-fef8360f658b)

### Can you link to any release notes, bugs, pull requests, or MDN pages related to this?

https://developer.mozilla.org/en-US/docs/Web/CSS/@page#margin_at-rules

https://learn.microsoft.com/en-us/deployedge/microsoft-edge-relnote-stable-channel#version-1310290348-november-14-2024

> @page margin boxes. Add support for page margin boxes, when printing a web document, or exporting it as PDF.
> 
> The @page margin boxes let you define the contents in the margin area of a page, for example to provide custom headers and footers, rather than using the built-in headers and footers generated by the browser.
> 
> A margin box is defined using an at-rule inside a CSS @page rule. The appearance and the contents of a margin box are specified with CSS properties inside the @page rule, including the content property. Counters are also supported, for page numbering. The specification defines two special counter names: page for the current page number and pages for the total number of pages.

### MDN URL

https://developer.mozilla.org/en-US/docs/Web/CSS/@page

### MDN metadata

<details>
<summary>MDN page report details</summary>

* Query: `css.at-rules.page`
* Report started: 2025-01-29T08:28:46.956Z

</details>
