### ISSUE TITLE
CSS text-decoration-skip-ink property

### ISSUE THREAD

**Issue by takamoso** [mdn/browser-compat-data#5242]
I think `text-decoration-skip-ink` property support from Opera 51.

tested on BrowserStack:
```css
@supports (text-decoration-skip-ink: auto) {
  .element {
    color: red;
  }
}
```
