### ISSUE TITLE
html.elements.summary - Compatibility with `display: list-item` appears to be outdated.

### ISSUE THREAD

**Issue by roydukkey** [mdn/browser-compat-data#9493]
#### What information was incorrect, unhelpful, or incomplete?
Compatibility with `display: list-item` appears to be outdated.

Chrome Version 89.0.4389.82 (Official Build) (x86_64) is using `display: list-item`

```css
details > summary:first-of-type {
    display: list-item;
    counter-increment: list-item 0;
    list-style: inside disclosure-closed;
}
```

#### What did you expect to see?

> Chrome currently doesn't use `display: list-item` on the `<summary>` element, so `display: block` will not automatically hide the disclosure widget. Instead, use the non-standard pseudo-element `::-webkit-details-marker` to change the disclosure widget in Chrome. See bug [590014](https://crbug.com/590014) for details.

This bug is marked as fixed.

<details>
<summary>MDN page report details</summary>

* Query: `html.elements.summary`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/summary
* Report started: 2021-03-17T18:18:55.944Z

</details>
